### ISSUE TITLE
地址选择器的数据源部分市没有区，例如广东省东莞市，广东省中山市

### ISSUE THREAD

**Issue by cs571393** [91renb/BRPickerView#104]
arealist都是空的

**Comment by 91renb** [comment]
参考民政部公布的数据：http://www.mca.gov.cn/article/sj/xzqh/2019/2019/201911051008.html
部分市是没有区的，只有县/镇/街道，没有区划代码。实际开发中可以以后台传的数据为准，项目内有一个标准就行，行政区划代码经常也在调整变化。

**Comment by cs571393** [comment]
@91renb  明白了
