### ISSUE TITLE
时间选择器月显示问题

### ISSUE THREAD

**Issue by yaoyongkang** [91renb/BRPickerView#114]
时间选择器中，当设定选择时间为2019-12-26后，弹出选择器，将年选中为2020年后，月日自动为最新时间，即显示为2020-01-02，当将年重新调整为2019时，当前选择器显示为2019-01-02，当点击确认时，选中时间却为2019-12-26而不是当前显示的2019-01-02，麻烦查看一下

**Comment by 91renb** [comment]
你好，这个问题已修复，我等下就更新上去

**Comment by 91renb** [comment]
你好，已上传 2.5.0 版本。pod更新一下就行

**Comment by yaoyongkang** [comment]
非常感谢🙏
