### ISSUE TITLE
BRDatePickerMode从NS_ENUM改为NS_OPTIONS灵活性会不会更高点

### ISSUE THREAD

**Issue by feixue299** [91renb/BRPickerView#127]

**Comment by 91renb** [comment]
NS_ENUM 定义通用枚举，NS_OPTIONS 定义位移枚举；一般枚举值需要用到按位（或2个及以上枚举值可多个存在）才使用NS_OPTIONS

**Comment by feixue299** [comment]
我的想法是这样的
```
typedef NS_OPTIONS(NSUInteger, BRDatePickerMode) {
    BRDatePickerModeY = 1 << 0,
    BRDatePickerModeM = 1 << 1,
    BRDatePickerModed = 1 << 2,
    BRDatePickerModeH = 1 << 3,
    BRDatePickerModem = 1 << 4,
};
```
通过这样的枚举可以达到多种组合的效果

**Comment by feixue299** [comment]
虽然说有可能有些组合不符合常规，但是最大可能的满足了多种模板的需求

**Comment by 91renb** [comment]
你推荐的这种思路是挺不错的。针对不同的应用场景，两种方式各有利弊：
1. 使用 `NS_OPTIONS` 一是扩展性和灵活性会比较强，二是就像你说的有些组合不符合常规，从设计层面考虑会有点不太严谨，使用起来没有 `NS_ENUM` 简单直观。
2. 使用的 `NS_ENUM`，一是方便把系统 `UIDatePicker` 里定义的几种日期样式合并在一起（里面有重复日期格式的情况），二是使用的时候也比较直观。这里定义的枚举类型已覆盖了绝大多数模板的需求。

**Comment by feixue299** [comment]
考不考虑加上```_Nullable，_Nonnull```这两个关键字，对swift的兼容更好些

**Comment by 91renb** [comment]
👍多谢提供建议，后期会不断优化的
