### ISSUE TITLE
BRDatePickerView中的resultBlock和changeBlock的使用问题

### ISSUE THREAD

**Issue by charsdavy** [91renb/BRPickerView#128]
/** 选择结果的回调 */
@property (nullable, nonatomic, copy) BRDateResultBlock resultBlock;
/** 滚动选择时触发的回调 */
@property (nullable, nonatomic, copy) BRDateResultBlock changeBlock;

按照注释所说，在用户点击“OK”按钮时才会调用resultBlock，在滚动时间选择时会调用changeBlock。但是现在表现是在选择过程中也会调用resultBlock。

这应该是个bug吧？

**Comment by 91renb** [comment]
只有设置`datePickerView.isAutoSelect = YES;`时，在选择过程中才会调用resultBlock。isAutoSelect默认为NO，默认情况下：在滚动时间选择时会调用changeBlock，点击“OK”按钮时才会调用resultBlock
