### ISSUE TITLE
是否能支持选中row字体和颜色设置？

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [91renb/BRPickerView#136]
eg:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/17978155/79127954-53767680-7dd5-11ea-94fc-49b316e40437.png">

**Comment by 91renb** [comment]
已实现该功能，请更新到最新版本进行使用。
```
// 设置选择器中间选中行的样式
BRPickerStyle *customStyle = [[BRPickerStyle alloc]init];
customStyle.selectRowTextFont = [UIFont boldSystemFontOfSize:20.0f];
customStyle.selectRowTextColor = [UIColor blueColor];
datePickerView.pickerStyle = customStyle;
```
![image](https://user-images.githubusercontent.com/23326671/80684888-f24ee280-8af8-11ea-8a5a-ce7e40ddaeef.png)

**Comment by liunianhuaguoyanxi** [comment]
1
