### ISSUE TITLE
顶部左右两个按钮 cancel 和 OK 为什么不能改成中文取消和确定😁

### ISSUE THREAD

**Issue by LeeZC** [91renb/BRPickerView#137]
如题，

**Comment by WennyLiang** [comment]
BRPickerStyle可以修改上边两个按钮的样式。。。demo里有详情

**Comment by LeeZC** [comment]
> BRPickerStyle可以修改上边两个按钮的样式。。。demo里有详情

哦哦哦，是是是，怪我眼拙了。。。。。。。
