### ISSUE TITLE
ios13暗黑模式下，背景和文字都是白色。

### ISSUE THREAD

**Issue by Quchangqing** [91renb/BRPickerView#140]

**Comment by 91renb** [comment]
你是不是设置了自定义样式，可以检查一下自定义样式的一些颜色，组件默认是适配深色模式的，

**Comment by coooliang** [comment]
请问暗黑模式下如何使用白色的主题呢？设置了自定义颜色为黑色，显示不出来，必须要设置pickerColor，alertViewColor为灰色或深色才看得到。。
`    UIColor *bgColor = [UIColor colorWithRed:0.5 green:0.5 blue:0.5 alpha:1];
    BRPickerStyle *customStyle = [[BRPickerStyle alloc]init];
    customStyle.titleBarColor = [UIColor whiteColor];
    customStyle.doneColor = [UIColor whiteColor];
    customStyle.doneTextColor = [UIColor blackColor];
    customStyle.cancelColor = [UIColor whiteColor];
    customStyle.cancelTextColor = [UIColor blackColor];
    customStyle.titleLineColor = [UIColor whiteColor];
    customStyle.titleTextColor = [UIColor blackColor];

    customStyle.pickerColor = bgColor;
    customStyle.alertViewColor = bgColor;

    customStyle.selectRowTextColor = [UIColor blackColor];
    customStyle.selectRowColor = [UIColor blackColor];
    customStyle.separatorColor = [UIColor blackColor];
    customStyle.pickerTextColor = [UIColor blackColor];
    customStyle.dateUnitTextColor = [UIColor blackColor];`

**Comment by coooliang** [comment]
https://github.com/91renb/BRPickerView/issues/162#issue-657966197
我的解决了
