### ISSUE TITLE
地址选择器的一个Bug，选择了省/市/区最后一个数据后，设置默认值会直接显示第一个数据

### ISSUE THREAD

**Issue by PrinceChen** [91renb/BRPickerView#143]
发现地址选择器一个bug，选择了省/市/区最后一个数据后，设置默认值会直接显示第一个数据

位置
文件 BRAddressPickerView.m
函数
#pragma mark - 设置默认选择的值
- (void)handlerDefaultSelectValue

line :164
if (idx == self.provinceModelArr.count - 1)
line: 187
if (idx == self.cityModelArr.count - 1) 
line: 210
if (idx == self.areaModelArr.count - 1)

我自己把这几行- 1 去掉就正常了

感谢提供如此利器，方便使用~

**Comment by 91renb** [comment]
已修复，请更新到最新版本进行使用。（提示：地址选择器推荐使用`selectIndexs`记录默认选择的位置）
