### ISSUE TITLE
希望支持日期区间、时间区间的选择

### ISSUE THREAD

**Issue by JuneCheng** [91renb/BRPickerView#151]
比如2020-06-02 至 2020-06-05 区间的一个日期选择

**Comment by 91renb** [comment]
使用属性`minDate`和`maxDate`，可以设置最小最大时间区间

**Comment by JuneCheng** [comment]
> 使用属性`minDate`和`maxDate`，可以设置最小最大时间区间

额，不好意思，没有把需求表达清楚。是弹出一个框，里面包含两个日期选择控件(一个开始日期，一个结束日期)。点击确定后，回调两个Date属性(一个是开始日期，一个是结束日期)

**Comment by 91renb** [comment]
这个需求是可以实现的，思路如下：
1.你可以自定义一个弹框视图（如：customAlertView）
2.再在`customAlertView`上添加左右两个容器视图（如：beginContainerView、endContainerView）
3.使用库中的`addPickerToView`方法将日期选择控件（beginDatePickerView、endDatePickerView）分别添加到上面的容器视图上。
4.联动控制：选择左边的时间后，可以重新设置右边日期选择器的日期区间，然后使用`reloadData`方法刷新一下右边的日期选择器即可。
