### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by ganweiming** [91renb/BRPickerView#153]
请问能否有方式可以支持app内设置国际化,例如app内仅支持简繁英三种语言,希望可以app内调整国际化,而不是跟随系统

**Comment by 91renb** [comment]
可以设置 language
`@property(nullable, nonatomic, copy) NSString *language;`

**Comment by ganweiming** [comment]
@91renb 想请问下具体设置吗,我用的是Swift,暂时没有找到BRDatePickerView内有language属性

**Comment by ganweiming** [comment]
@91renb 已找到,在pickerStyle内,感谢帮助
