### ISSUE TITLE
接手的前任的项目用了你的这个框架 但是你方法好像改了 她用的是没有指定版本的pod 我现在一个个试都不合适 醉了 不知道能不能联系上你 改别人代码真坑啊  版本迭代稍不注意就可能是大坑 

### ISSUE THREAD

**Issue by CoderAquarius** [91renb/BRPickerView#158]
接手的前任的项目用了你的这个框架 但是你方法好像改了 她用的是没有指定版本的pod 我现在一个个试都不合适 醉了 不知道能不能联系上你 改别人代码真坑啊  版本迭代稍不注意就可能是大坑  可以加你微信或者qq吗 急死了 这一个错 我开始以为是代码的原因 各种试 发现可能是用的库的版本的原因 哎 奈何不是自己一手的项目 烦人 还各种不规范  我企鹅 1264727563 Apple 或者你有群吗 大佬 拜托了  终于体验到 为啥大公司的项目一般不轻易使用别人的轮子 照片如下  
<img width="957" alt="WechatIMG4" src="https://user-images.githubusercontent.com/13150300/84766102-d5b42e80-b002-11ea-8865-9a633b71e7dc.png">

**Comment by 91renb** [comment]
![image](https://user-images.githubusercontent.com/23326671/84774075-e4551280-b00f-11ea-940e-e83a2d845edd.png)
如果编译还有问题，记得clean一下，重新pod一下
