### ISSUE TITLE
ios 14 KVC 用不了了

### ISSUE THREAD

**Issue by ThinkDifferents** [91renb/BRPickerView#159]
// textColor 隐藏属性，使用KVC赋值
        [self.datePicker setValue:self.pickerStyle.pickerTextColor forKey:@"textColor"];

// 报错
-[_UIDatePickerIOSCompactView _setTextColor:]: unrecognized selector sent to instance 0x10bc25720

不清楚别的KVC 能不能用， 反正这个不能用了

**Comment by 91renb** [comment]
这个已去掉，库内没有其它地方使用私有属性
