### ISSUE TITLE
一些命名能否加前缀区别，不然会遇见重复定义问题

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [91renb/BRPickerView#161]
eg: SCREEN_BOUNDS SCREEN_HEIGHT

// 屏幕大小、宽、高
#ifndef SCREEN_BOUNDS
#define SCREEN_BOUNDS [UIScreen mainScreen].bounds
#endif
#ifndef SCREEN_WIDTH
#define SCREEN_WIDTH [UIScreen mainScreen].bounds.size.width
#endif
#ifndef SCREEN_HEIGHT
#define SCREEN_HEIGHT [UIScreen mainScreen].bounds.size.height
#endif

**Comment by 91renb** [comment]
常见的宏定义，建议都加个 `#ifndef` 宏定义判断，就不会出现重复定义的情况；如果都加前缀去区分，在项目中使用起来会比较混乱，没有统一规范，可维护性也不太好。

**Comment by liunianhuaguoyanxi** [comment]
我的意思是 变为BR_SCREEN_BOUNDS  
因为你的项目中很多都是有前缀的
// 状态栏的高度(20 / 44(iPhoneX))
#define BR_STATUSBAR_HEIGHT ([UIApplication sharedApplication].statusBarFrame.size.height)
#define BR_IS_iPhoneX ((BR_STATUSBAR_HEIGHT == 44) ? YES : NO)
// 底部安全区域远离高度
#define BR_BOTTOM_MARGIN ((CGFloat)(BR_IS_iPhoneX ? ((SCREEN_WIDTH < SCREEN_HEIGHT) ? 34 : 21) : 0))

小部分是没有前缀的，这边不会报错但是会有告警。
