### ISSUE TITLE
时间间隔能不能整点开始 5-10-15-20  10-20-30-40-50  15-30-45 不用从当前时间算起

### ISSUE THREAD

**Issue by mrwangapple** [91renb/BRPickerView#164]
时间间隔能不能整点开始 5-10-15-20  10-20-30-40-50  15-30-45 不用从当前时间算起

**Comment by 91renb** [comment]
可以设置默认的minDate、maxDate、selectDate进行控制

**Comment by mrwangapple** [comment]
自己判断时间在那个区间吗？




| |
王志博
邮箱：mrwangapple@163.com
|

签名由 网易邮箱大师 定制

在2020年07月28日 18:44，Renbo 写道：

可以设置默认的minDate、maxDate、selectDate进行控制

**Comment by 91renb** [comment]
比如设置：时间区间为 [minDate, maxDate]，时间间隔为5；选择的时间就是：minDate、minDate + 5、minDate + 10、minDate + 15、minDate + 20、... ... 、maxDate
