### ISSUE TITLE
demo一直报错

### ISSUE THREAD

**Issue by 1510872953** [91renb/BRPickerView#166]
demo一直报错哦

**Comment by 91renb** [comment]
你开发环境是什么，Xcode和iOS版本多少？

**Comment by 1510872953** [comment]
xcode10.1
macos 14.5.1

**Comment by 1510872953** [comment]
忘了，周一去公司看看哈，家里也没办法知道公司电脑的系统版本哦

**Comment by 91renb** [comment]
你Xcode版本太老了，请使用Xcode11以上版本进行编译。不然适配深色模式的API编译不过
