### ISSUE TITLE
BRBaseView

### ISSUE THREAD

**Issue by 295060456** [91renb/BRPickerView#167]
希望在日期选择，背后显示年。
demo：YWAlertView-master https://github.com/flyOfYW/YWAlertView

**Comment by 295060456** [comment]
> 希望在日期选择，背后显示年。
> demo：YWAlertView-master https://github.com/flyOfYW/YWAlertView

**Comment by 91renb** [comment]
可以自定义弹框样式来实现：先自定义好弹框视图及背景样式，再使用`addPickerToView` 方法把 pickerView 滚轮添加上去，并 设置 pickerView 的背景颜色 为 clearColor。即可实现你的需求。
