### ISSUE TITLE
 设置 minuteInterval 直接就崩掉了(必现)

### ISSUE THREAD

**Issue by lixiang-8023** [91renb/BRPickerView#170]
如题，我想设置 BRDatePickerModeHM 的分钟间隔 比如 0 10 20 这样的，但是在 minuteInterval 后直接就崩掉了

**Comment by 91renb** [comment]
需要设置一下：datePickerView.selectDate = [NSDate br_setHour:0 minute:0]; 下个版本我会优化一下

**Comment by 91renb** [comment]
已升级，pod更新一下
