### ISSUE TITLE
swift 多级联动 点击确定 没有回调 BRStringPickerView dealloc

### ISSUE THREAD

**Issue by lczalh** [91renb/BRPickerView#171]

**Comment by 91renb** [comment]
参见 #163，稍后会更新

**Comment by lczalh** [comment]
![C8307187-FE5C-4EB3-911A-113C229D1CED](https://user-images.githubusercontent.com/29446825/89406489-d1c5a280-d74f-11ea-99c6-4160e54e9f7d.png)
我添加了 这个条件。我打印这个类型 确实是BRStringPickerComponentLinkage  但是还是没进去 不知道什么原因。

**Comment by lczalh** [comment]
重启Xcode 才可以的。  麻烦尽快更新 急用谢谢。

**Comment by 91renb** [comment]
好的，我再测试一下，中午之前一并更新

**Comment by 91renb** [comment]
已更新，pod更新一下

**Comment by lczalh** [comment]
好的
