### ISSUE TITLE
我又帮你优化了一个功能。

### ISSUE THREAD

**Issue by 295060456** [91renb/BRPickerView#172]
1、在BRBaseView里面加一个方法：
-(void)doneBtnCanBeClick:(BOOL)click{
    self.doneBtn.userInteractionEnabled = click;
    self.doneBtn.alpha = click ? 1 : 0.4;
}

在doneBtn 初始化里面加上
        //最开始是不能够被点击的
        _doneBtn.userInteractionEnabled = NO;
        _doneBtn.alpha = 0.4;

2、在 AddressPickerView、DatePickerView、StringPickerView里面都加上：
show方法里见面加[self doneBtnCanBeClick:NO];
3、
 AddressPickerView、DatePickerView：
// 滚动完成后，执行block回调
        if (self.resultBlock) {
            [self doneBtnCanBeClick:YES];
            self.resultBlock(self.mSelectDate, self.mSelectValue);
        }

StringPickerView：
        if (self.pickerMode == BRStringPickerComponentSingle) {
            if (self.resultModelBlock) {
                [self doneBtnCanBeClick:YES];
                self.resultModelBlock([self getResultModel]);
            }
        } else if (self.pickerMode == BRStringPickerComponentMulti) {
            if (self.resultModelArrayBlock) {
                [self doneBtnCanBeClick:YES];
                self.resultModelArrayBlock([self getResultModelArr]);
            }
        }

**Comment by 91renb** [comment]
考虑到库的通用性和灵活性，这类需求都可以通过使用 `addPickerToView` 方法自定义弹框视图来实现，自定义的取消按钮和确定按钮，自己可以灵活的去控制
