### ISSUE TITLE
UIWindow 的事情

### ISSUE THREAD

**Issue by 295060456** [91renb/BRPickerView#173]
发现你没有对iOS 13进行适配：
static inline UIWindow * getMainWindow(){
    UIWindow *window = nil;
    if (@available(iOS 13.0, *)) {
        window = [SceneDelegate sharedInstance].window;
    }else{
        window = UIApplication.sharedApplication.delegate.window;
//        [UIApplication sharedApplication].keyWindow 
    }return window;
}

在 SceneDelegate里面
static SceneDelegate *static_sceneDelegate = nil;
+(SceneDelegate *)sharedInstance{
    @synchronized(self){
        if (!static_sceneDelegate) {
            static_sceneDelegate = SceneDelegate.new;
        }
    }return static_sceneDelegate;
}

**Comment by 91renb** [comment]
多谢提醒，新版本对已针对iOS13和iOS14进行了适配

**Comment by bk97531** [comment]
> 多谢提醒，新版本对已针对iOS13和iOS14进行了适配

建议添加可以自定义传入window的,现在获取window的方法不是很合理,last的不一定就是当前需要显示的

**Comment by 91renb** [comment]
新增了如下属性：
```
/** 组件的父视图：可以传 自己获取的 keyWindow，或页面的 view */
@property (nullable, nonatomic, strong) UIView *keyView;
```
请更新到最新版本进行使用
