### ISSUE TITLE
iOS14 闪退

### ISSUE THREAD

**Issue by lzx668** [91renb/BRPickerView#174]
[pickerView.subviews objectAtIndex:2] 这里数组越界。
还有iOS14 keyWindow这个属性会废弃掉，解决完上面的闪退问题还要修改这里的展示问题。

**Comment by 91renb** [comment]
库你使用的是哪个版本

**Comment by lzx668** [comment]
库是18年下的，刚用你最新版本2.6.8的库，没有这个问题了
