### ISSUE TITLE
行高比较大的时候，selectRowTextColor除了最后一行设置成功，其他行没有没有效果。

### ISSUE THREAD

**Issue by amycliny** [91renb/BRPickerView#177]
在demo上试过了，只有“其他”选中的时候为白色（也就是最后一行），代码如下，rowHeight <= 70没有问题，是我漏掉了什么吗？   

// 性别
            BRStringPickerView *stringPickerView = [[BRStringPickerView alloc]init];
            stringPickerView.pickerMode = BRStringPickerComponentSingle;
//            stringPickerView.title = @"请选择性别";
            stringPickerView.dataSourceArr = @[@"男", @"女", @"其他"];
            stringPickerView.selectIndex = self.genderSelectIndex ;
            stringPickerView.resultModelBlock = ^(BRResultModel *resultModel) {
                self.genderSelectIndex = resultModel.index;
                self.infoModel.genderStr = resultModel.value;
                textField.text = resultModel.value;
            };
            
            BRPickerStyle *customStyle = [[BRPickerStyle alloc]init];
                             customStyle.selectRowTextFont = [UIFont systemFontOfSize:33];
                             customStyle.pickerTextFont = [UIFont systemFontOfSize:33];
                             customStyle.selectRowTextColor = UIColor.whiteColor;
                             customStyle.pickerTextColor = [UIColor colorWithWhite:0xffffff alpha:0.4];
                             customStyle.separatorColor = UIColor.blackColor;
                             customStyle.rowHeight = 78;
                             customStyle.pickerColor = UIColor.grayColor;
                             stringPickerView.pickerStyle = customStyle;
                      
            [stringPickerView show];

**Comment by amycliny** [comment]
补两张图：
<img width="381" alt="wrong@2x" src="https://user-images.githubusercontent.com/15085638/91164600-e15a5a80-e701-11ea-8655-3de73df44679.png">
<img width="378" alt="correct@2x" src="https://user-images.githubusercontent.com/15085638/91164605-e4554b00-e701-11ea-86fb-cff6f5d26663.png">

**Comment by 91renb** [comment]
测了一下rowHeight大于70时是有问题，这个问题已解决，晚上会统一升级更新
