### ISSUE TITLE
我这个获取时间好像需要调整时区了

### ISSUE THREAD

**Issue by myDonghao** [91renb/BRPickerView#183]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/20014338/93048127-b922a380-f690-11ea-8579-4af3f7a92d99.png">

**Comment by 91renb** [comment]
date时间默认都是零时区时间（即UTC世界标准时间），与当前时间会有8小时时差，是正常的。
NSDate类型的时间显示的是UTC标准时间，转成NSString类型的时间显示的就是当前时区的时间。

**Comment by myDonghao** [comment]
嗯嗯，多谢解答，我说这是咋回事呢！😅
