### ISSUE TITLE
日期选择器联动不正确的问题&&自定义字符串是否显示在第一行

### ISSUE THREAD

**Issue by zhongdom** [91renb/BRPickerView#184]
1. 设置当前时间为最小日期，比如现在为2020-09-16，将月份滚动到11月（第三行），此时滑动年份，正常显示应该月份不变，但是现在月份会跳到3月（第三行）
2. 现在日期选择器自定义字符串是最后一行，是否可以增加一个选项放在第一行？

**Comment by 91renb** [comment]
已解决，新增添加自定义字符串属性：firstRowContent 和 lastRowContent。请升级到最新版本进行使用
