### ISSUE TITLE
IOS14  EXEC ' BRStringPickerView.showStringPicker'   CRASH!!!!

### ISSUE THREAD

**Issue by 429329513wanting** [91renb/BRPickerView#188]
BRStringPickerView.showStringPicker(withTitle: "请选择支付类型", dataSource: labs, defaultSelValue: nil, isAutoSelect: false, themeColor: UIColor.btnMainColor) { (str) in
            
            let index = (labs as NSArray).index(of: (str as! String))
            self.curPay = self.commonLab!.channelPay.get(at: index)
            btn.setTitle(self.curPay?.label, for: .normal)
        }

RESULT=======CRASH Here '   
 ((UIView *)[pickerView.subviews objectAtIndex:2]).backgroundColor = [UIColor colorWithRed:195/255.0 green:195/255.0 blue:195/255.0 alpha:1.0];'
in class 'BRStringPickerView'

// 自定义 pickerView 的 label
- (UIView *)pickerView:(UIPickerView *)pickerView viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(nullable UIView *)view {
    
    //设置分割线的颜色
    ((UIView *)[pickerView.subviews objectAtIndex:1]).backgroundColor = [UIColor colorWithRed:195/255.0 green:195/255.0 blue:195/255.0 alpha:1.0];
    ((UIView *)[pickerView.subviews objectAtIndex:2]).backgroundColor = [UIColor colorWithRed:195/255.0 green:195/255.0 blue:195/255.0 alpha:1.0];
    
    UILabel *label = [[UILabel alloc]initWithFrame:CGRectMake(0, 0, self.alertView.frame.size.width / 3, 35.0f * kScaleFit)];
    label.backgroundColor = [UIColor clearColor];
    label.textAlignment = NSTextAlignmentCenter;
    //label.textColor = [UIColor redColor];
    label.font = [UIFont systemFontOfSize:18.0f * kScaleFit];
    // 字体自适应属性
    label.adjustsFontSizeToFitWidth = YES;
    // 自适应最小字体缩放比例
    label.minimumScaleFactor = 0.5f;
    if (self.type == BRStringPickerComponentSingle) {
        label.text = self.dataSourceArr[row];
    } else if (self.type == BRStringPickerComponentMore) {
        label.text = self.dataSourceArr[component][row];
    }
    
    return label;
}

**Comment by 91renb** [comment]
请升级到最新版本进行使用，UIPickerView 在 iOS14 上子视图有调整，老版本设置的分割线的方式已经不兼容。

**Comment by 429329513wanting** [comment]
> 请升级到最新版本进行使用，UIPickerView 在 iOS14 上子视图有调整，老版本设置的分割线的方式已经不兼容。

界面很多地方用了这个API，我直接把设置颜色那里给注释了。也能运行,没闪退了。

**Comment by 91renb** [comment]
有时间建议更新一下库使用最新版本，新版本更加稳定，也便于后期维护。如果页面中使用比较多修改起来比较麻烦，也可以 新建 BRStringPickerView + BRAdd 分类，使用新版本二次封装你调用的showStringPicker()方法，这样便于后期维护。

**Comment by 429329513wanting** [comment]
> 有时间建议更新一下库使用最新版本，新版本更加稳定，也便于后期维护。如果页面中使用比较多修改起来比较麻烦，也可以 新建 BRStringPickerView + BRAdd 分类，使用新版本二次封装你调用的showStringPicker()方法，这样便于后期维护。

好的，thank you
