### ISSUE TITLE
iOS14 适配的问题

### ISSUE THREAD

**Issue by baiyidjp** [91renb/BRPickerView#189]
手机系统iOS14，PickerView 2.7.2 

1. iOS14系统表现 pickerView的宽度没有占用全屏的宽度，右边有空间。
2. 怎么设置多语言的环境

谢谢

**Comment by 91renb** [comment]
1.pickerView的宽度默认为当前 keyWindow 的宽度，为了适配多屏默认获取的不是屏幕的宽度。可以自己使用下面属性：
```
/** 组件的父视图：可以传 自己获取的 keyWindow，或页面的 view */
@property (nullable, nonatomic, strong) UIView *keyView;
``` 
如：`datePickerView.keyView = self.view;` // 将组件 datePickerView 添加到 self.view 上，默认是添加到 keyWindow 上

2.多语言环境在 `BRPickerStyle.h` 中有提供如下属性
```
/**
 *  设置语言（不设置或为nil时，将随系统的语言自动改变）
 *  language: zh-Hans（简体中文）、zh-Hant（繁体中文）、en（英语 ）
 */
@property(nullable, nonatomic, copy) NSString *language;
```

**Comment by baiyidjp** [comment]
好的 谢谢！ 马上试试

**Comment by baiyidjp** [comment]
如图，中英文可以了。但是右边的空隙还是比左边的大，并没有居中，我也传了当前controller的view给keyView了。


![image](https://user-images.githubusercontent.com/12672573/94095946-6184f480-fe55-11ea-96bc-bdafc0b13217.png)

![image](https://user-images.githubusercontent.com/12672573/94096156-f4be2a00-fe55-11ea-81c4-8b66d200d19c.png)

**Comment by 91renb** [comment]
`BRDatePickerModeDate` 是 UIDatePicker 系统自带的样式，暂无法自定义控制；
可以设置 `pickerMode == BRDatePickerModeYMD`，这个是 UIPickerView 封装的样式，提供了很多自定义样式属性

**Comment by baiyidjp** [comment]
> `BRDatePickerModeDate` 是 UIDatePicker 系统自带的样式，暂无法自定义控制；
> 可以设置 `pickerMode == BRDatePickerModeYMD`，这个是 UIPickerView 封装的样式，提供了很多自定义样式属性

好的 设置完可以居中了。谢谢

**Comment by 91renb** [comment]
多谢你的提醒，刚才测试了一下`BRDatePickerModeDate`也是可以实现居中。
在iOS14里默认设置 datePicker 的 frame 宽高会不生效。需要先设置 datePickerMode，再设置  frame  才会生效，估计是iOS14的一个小bug。后面我会优化更新一下~

**Comment by baiyidjp** [comment]
> 多谢你的提醒，刚才测试了一下`BRDatePickerModeDate`也是可以实现居中。
> 在iOS14里默认设置 datePicker 的 frame 宽高会不生效。需要先设置 datePickerMode，再设置 frame 才会生效，估计是iOS14的一个小bug。后面我会优化更新一下~

中文下这个时间： 年的显示有点被切掉了一点 机型是iPhoneX

![image](https://user-images.githubusercontent.com/12672573/94107730-a2d6cd80-fe70-11ea-8652-c11ee0959a85.png)

**Comment by 91renb** [comment]
已适配iOS14显示样式，同iOS14之前版本显示样式一致，不需要额外再设置API，请更新到最新版本进行使用

**Comment by baiyidjp** [comment]
已经使用最新版本，谢谢
