### ISSUE TITLE
我设置选择时间的格式为日时分dd HH:mm，当设置最小时间和最大时间夸月后，时间选择器会崩溃

### ISSUE THREAD

**Issue by AriesL-ux** [91renb/BRPickerView#193]
我设置选择时间的格式为日时分dd HH:mm，当设置最小时间和最大时间夸月后，时间选择器会崩溃
建议添加 日时分的时间格式

**Comment by 91renb** [comment]
设置 `minDate/maxDate/selectDate` 的时间格式要与`pickerMode`的格式相对应，目前选择器没有提供【日时分】类型的日期选择。这种类型应用场景不多，如果需要【日时分】类型的日期选择，可以使用 `BRStringPickerView` 自定义数据源来实现
