### ISSUE TITLE
城市选择三级联动的有些城市下面没有镇区

### ISSUE THREAD

**Issue by Mr-lins** [91renb/BRPickerView#194]
BRCity.json数据源是否可以同步一下高德的城市列表

**Comment by 91renb** [comment]
数据来源于民政部：http://www.mca.gov.cn//article/sj/xzqh/2020/2020/20200908007001.html
是没有县/街道/镇区、及港澳台数据，省市区数据每个月都会更新调整，实际开发中一般都是从后台获取，根据项目需求 公司内部有个标准就行。使用 BRAddressPickerView 或 BRStringPickerView 都支持自己传入地区数据源，实现三级联动选择。
