### ISSUE TITLE
请问能否在月和日这两个选择滚轮第一个数据加上全部吗？

### ISSUE THREAD

**Issue by ws1227** [91renb/BRPickerView#203]
请问能否在月和日这两个选择滚轮第一个数据加上全部吗？
例如 全部

**Comment by ws1227** [comment]
例如
全部
1月 
2月
3月
就是添加个自定义元素

**Comment by ws1227** [comment]
我看到有这样一个firstRowContent属性，但它只是支持第一列 如何支持每一列呢

**Comment by 91renb** [comment]
如果是简单的日期选择（如：月日选择），也可以使用 `BRStringPickerView` 自己传数据源来实现类似于时间选择器的效果

**Comment by ws1227** [comment]
嗯，昨天我也这么想了，也可以实现
