### ISSUE TITLE
timeZone 设置导致日期起止时间显示不正确

### ISSUE THREAD

**Issue by FunnyerFeng** [91renb/BRPickerView#277]
当传入timeZone 时，因为NSDate+BRPickerView中的br_calendar的timeZone 没有设置成传入的timeZone，导致日历的起止时间显示不正确

**Comment by FunnyerFeng** [comment]
使用的版本：pod 'BRPickerView', '2.7.8'

**Comment by FunnyerFeng** [comment]
新版本代码中并没有修复的代码

**Comment by 91renb** [comment]
可以使用下面方法来创建起止时间
/// ---------------- 创建 date ----------------
/** 通过 NSDateComponents对象 来创建 NSDate对象（可以设置时区） */
+ (nullable NSDate *)br_setDateFromComponents:(NSDateComponents *)components timeZone:(NSTimeZone *)timeZone;
