### ISSUE TITLE
取消的时候没有重置

### ISSUE THREAD

**Issue by JKjiangnan** [91renb/BRPickerView#28]
picker 选择后点 取消按钮和确认按钮好像没啥区别啊

**Comment by renboss** [comment]
点确认按钮会执行resultBlock回调，可以在resultBlock中获取选择的值。
点取消按钮或背景会执行cancelBlock回调，这个过程只会将选择器视图从界面移除，不会回传选择的值。你可以根据自己的需求，在cancelBlock中处理自己页面上的一些变化。
