### ISSUE TITLE
地址选择器确认选择后，能新增返回省市区对应的ID吗？

### ISSUE THREAD

**Issue by XCmaxwell** [91renb/BRPickerView#29]
1.地址选择器确认选择后，能新增返回省市区对应的ID？虽然现在也可以遍历拿到，感觉还是在选择的时候就返回更好。
typedef void(^BRAddressResultBlock)(NSArray *selectAddressArr, NSArray *selectIdArray)

2.在BRAddressPickerView.m文件中
// 根据 省索引和城市索引 获取 区域名数组
- (NSArray *)getAreaNameArray:(NSInteger)provinceIndex cityIndex:(NSInteger)cityIndex

这个方法能否直接根据cityIndex，去取模型中对应的属性，而不要去遍历？其他类似方法也一样处理下
十分感谢

**Comment by 91renb** [comment]
你好，已更新至2.1.3版本，修改回调参数如下：
typedef void(^BRAddressResultBlock)(BRProvinceModel *province, BRCityModel *city, BRAreaModel *area);
提示：修改了地址数据源（BRCity.plist）文件中的key，之前的id就是现在的code。
