### ISSUE TITLE
2.2.0版本，默认选中时间为空，最大时间为当前时间断言问题

### ISSUE THREAD

**Issue by bangjier** [91renb/BRPickerView#32]
当我传的默认选中时间为空时，我看你self.selectDate是取的当前时间，我最大时间也是传的当前时间，如下图所示：
![wechatimg10655](https://user-images.githubusercontent.com/13373708/38230570-1f0bbf2c-3741-11e8-9882-d85b8f4e8053.jpeg)
两个值比较结果为NSOrderedDescending
这样你下面判断@"默认选择的日期不能大于最大日期！"时就会断到这里
![wechatimg10656](https://user-images.githubusercontent.com/13373708/38230618-58f0309c-3741-11e8-9b85-4fc059009d55.jpeg)

**Comment by 91renb** [comment]
您好，非常感谢你指出这个问题，这个bug已经修复了。
出现这个bug的原因是，在比较两个时间时没有指定比较级数（即这里应该按 yyyy-MM-dd HH:mm:ss 进行比较）
NSDate *date1 = [NSDate date];
NSDate *date2 = [NSDate date];
NSDate *date3 = [NSDate date];

不指定比较级数时，date1 < date2 < date3
指定比较级数（yyyy-MM-dd HH:mm:ss）时，date1 = date2 = date3
