### ISSUE TITLE
作者是不是忘了添加UIColor的分类呀，报错的行数如下显示

### ISSUE THREAD

**Issue by aqiejiao** [91renb/BRPickerView#78]
+ (instancetype)pickerStyleWithDarkModel {
    BRPickerStyle *customStyle = [[self alloc]init];
    // 自定义主题样式（适配深色模式）
    if (@available(iOS 13.0, *)) {
        customStyle.maskColor = [[UIColor labelColor] colorWithAlphaComponent:0.2];
        customStyle.titleBarColor = [UIColor systemBackgroundColor];
        customStyle.leftTextColor = [UIColor labelColor];
        customStyle.rightTextColor = [UIColor labelColor];
        customStyle.titleTextColor = [UIColor placeholderTextColor];
        customStyle.titleLineColor = [UIColor quaternaryLabelColor];
        
        customStyle.pickerColor = [UIColor systemBackgroundColor];
        customStyle.pickerTextColor = [UIColor labelColor];
        customStyle.separatorColor = [UIColor separatorColor];
    }
    
    return customStyle;
}

**Comment by 91renb** [comment]
这是iOS13以后，系统新增的动态颜色，主要是适配深色模式用，需要升级Xcode11以上进行编译
