### ISSUE TITLE
设置地址标题颜色titleTextColor没变化

### ISSUE THREAD

**Issue by 2487464453** [91renb/BRPickerView#83]

**Comment by 91renb** [comment]
你好，你可以先把设置 title 放到最后，这样也能解决颜色的显示；我后期会及时优化的。

// 自定义弹框样式
BRPickerStyle *customStyle = [[BRPickerStyle alloc]init];
customStyle.titleTextColor = [UIColor blueColor];
stringPickerView.pickerStyle = customStyle;
            
stringPickerView.title = @"自定义多列字符串"; // 这句代码放到后面

**Comment by 2487464453** [comment]
能提取 城市名字字体大小么 因为字体font 18大小比例适应 在scale = 3的手机上 字体有点大 跟自己写的页面 font = 15 有点不友好

**Comment by 91renb** [comment]
可以的，我下午会统一更新的

**Comment by 91renb** [comment]
已更新，你看下还有没有什么问题

**Comment by 2487464453** [comment]
没问题了,非常nice



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "91renb"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 下午5:01
收件人: "91renb/BRPickerView"<BRPickerView@noreply.github.com&gt;; 
抄送: "&amp;#x1F33F;"<2487464453@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [91renb/BRPickerView] 设置地址标题颜色titleTextColor没变化 (#83)




已更新，你看下还有没有什么问题

**Comment by 91renb** [comment]
好的😊

**Comment by 2487464453** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"91renb"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 下午5:36
收件人:&nbsp;"91renb/BRPickerView"<BRPickerView@noreply.github.com&gt;;
抄送:&nbsp;"🌿"<2487464453@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [91renb/BRPickerView] 设置地址标题颜色titleTextColor没变化 (#83)




好的
