### ISSUE TITLE
Right button too small to fit label

### ISSUE THREAD

**Issue by skuske** [91renb/BRPickerView#84]
Button sizes should adopt to the button label, otherwise text gets cropped:

![button](https://user-images.githubusercontent.com/12996815/67848360-c7151780-fb04-11e9-9d8e-04ca853db0ee.jpeg)

**Comment by 91renb** [comment]
/** customize the left button width /
@property (nonatomic, assign) CGFloat leftBtnWidth;
/ customize the right button width */
@property (nonatomic, assign) CGFloat rightBtnWidth;
