### ISSUE TITLE
BRPickerView/AddressPickerView/BRPickerView.bundle 路径有问题

### ISSUE THREAD

**Issue by lyuxxx** [91renb/BRPickerView#90]
如果没有引用AddressPickerView subspec，不会引入这个bundle，导致代码报错
![屏幕快照 2019-11-04 下午12 00 55](https://user-images.githubusercontent.com/19743675/68099002-e17f3480-fefa-11e9-953d-bbc9f4bde704.png)

**Comment by 91renb** [comment]
你好，这个问题已解决。请pod更新一下

**Comment by lyuxxx** [comment]
好的
