### ISSUE TITLE
swift使用BRPickerStyle闪退

### ISSUE THREAD

**Issue by cs571393** [91renb/BRPickerView#91]
pickerStyle = BRPickerStyle(themeColor: kMainColor)
pickerStyle.cancelColor = UIColor.clear

**Comment by cs571393** [comment]
用2.3.6版本的leftcolor就不会有问题

**Comment by 91renb** [comment]
你排查一下错误原因是什么，我这边测试是没有问题的

**Comment by cs571393** [comment]
@91renb -[BRPickerStyle setCancelColor:]: unrecognized selector sent to instance 0x28296e680
报错信息是这样
我猜是不是要重写写set方法

**Comment by cs571393** [comment]
我clean完，删除重新来，就可以。

**Comment by 91renb** [comment]
好的呢
