### ISSUE TITLE
iPhone X + XS + XR: cancel button landscape x position

### ISSUE THREAD

**Issue by skuske** [91renb/BRPickerView#93]
If the picker is presented in landscape view, the X position of the cancel button should pay attention to the `safeAreaInsets` on iPhone X, XS and XR devices, otherwise the cancel button is cut off on the left:

```
    UIEdgeInsets safeInsets = UIEdgeInsetsZero;
    safeInsets = ([UIApplication sharedApplication].delegate).window.safeAreaInsets;
    CGRect rectFrame=customStyle.cancelBtnFrame;
    rectFrame.origin.x+=safeInsets.left;
    customStyle.cancelBtnFrame=rectFrame;
```
 Maybe that should be implemented by default ... :o)

**Comment by 91renb** [comment]
This problem has been solved. Please update version 2.4.2. Thanks! :o)
